"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AO2XP.py']
DATA_FILES = []
OPTIONS = dict(
	includes = [
		"zlib",
		"sip",
		"PyQt4",
		"PyQt4._qt",
		"PyQt4.QtCore",
		"PyQt4.QtGui",
	],

	excludes = [
		"PyQt4.QtDesigner",
		"PyQt4.QtNetwork",
		"PyQt4.QtOpenGL",
		"PyQt4.QtScript",
		"PyQt4.QtSql",
		"PyQt4.QtTest",
		"PyQt4.QtWebKit",
		"PyQt4.QtXml",
		"PyQt4.phonon",
	],

	packages = [
	],

	argv_emulation = False
)

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
